oauthClient:
  redirectUris:
    - http://${CLI_OKTA_REDIRECT_SCHEME}:/callback
  applicationType: native

directions: |+2
  Okta configuration written to: auth.config.js

  Build this example using npm:

    npm install

  Run instructions for iOS:
    • cd ios && pod install && cd ..
    • npx react-native run-ios
    - or -
    • Open ios/SecureApp.xcworkspace in Xcode or run "xed -b ios"
    • Hit the Run button

  Run instructions for Android:
    • Have an Android emulator running (quickest way to get started), or a device connected.
    • npx react-native run-android

  Run instructions for Windows and macOS:
    • See https://aka.ms/ReactNative for the latest up-to-date instructions.
